github.com:
    user: CarterFaceySmith
    git_protocol: ssh
    users:
        CarterFaceySmith:
            oauth_token: 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
    oauth_token: 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
